version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - kafka-net

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    volumes:
      - ./producer:/usr/src/app
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - kafka-net

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    volumes:
      - ./consumer:/usr/src/app
    depends_on:
      - kafka
      - zookeeper

    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
